//Courses
export const FETCH_COURSES_START = 'FETCH_COURSES_START';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAIL = 'FETCH_COURSES_FAIL';
export const INCREASE_INDEX_PAGE = 'INCREASE_INDEX_PAGE';
export const STOP_LOADING_COURSES = 'STOP_LOADING_COURSES';
export const IS_LOADING_COURSES = 'IS_LOADING_COURSES';
export const RESET_DATA_COURSES = 'RESET_DATA_COURSES';

//Course
export const FETCH_COURSE_START = 'FETCH_COURSE_START';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSE_FAIL = 'FETCH_COURSE_FAIL';
