export const COURSE_FETCHING_DATA = 'COURSE_FETCHING_DATA'
export const COURSE_FETCHING_DATA_SUCCESS = 'COURSE_FETCHING_DATA_SUCCESS'
export const COURSE_FETCHING_DATA_FAILURE = 'COURSE_FETCHING_DATA_FAILURE'