export const COURSE_FETCHING_DATA = 'COURSE_FETCHING_DATA';
export const COURSE_FETCHING_DATA_SUCCESS = 'COURSE_FETCHING_DATA_SUCCESS';
export const COURSE_FETCHING_DATA_FAILURE = 'COURSE_FETCHING_DATA_FAILURE';
export const COURSE_RATINGS = 'COURSE_RATINGS';
export const INCREASE_INDEX_PAGE = 'INCREASE_INDEX_PAGE';
export const STOP_LOAD = "STOP_LOAD";
export const IS_LOADING = 'IS_LOADING';