export const FETCHING_DATA_SECTION = 'FETCHING_DATA_SECTION';

export const FETCHING_DATA_SUCCESS_SECTION = 'FETCHING_DATA_SUCCESS_SECTION';

export const FETCHING_DATA_FAILURE_SECTION = 'FETCHING_DATA_FAILURE_SECTION';
