export const VIDEO_FETCH_REQUESTED = 'VIDEO_FETCH_REQUESTED';
export const VIDEO_FETCH_FULFILLED = 'VIDEO_FETCH_FULFILLED';
export const VIDEO_FETCH_REJECTED = 'VIDEO_FETCH_REJECTED';

export default {
  VIDEO_FETCH_FULFILLED,
  VIDEO_FETCH_REQUESTED,
  VIDEO_FETCH_REJECTED,
};
